services:
  apache:
    image: ${DOCKER_REGISTRY:-localhost}/reliquary:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=15&charset=utf8
      MAILER_DSN: ${MAILER_DSN}
    volumes:
      - /etc/letsencrypt/live/santasreliquias.com.br/fullchain.pem:/etc/apache2/ssl/apache.crt
      - /etc/letsencrypt/live/santasreliquias.com.br/privkey.pem:/etc/apache2/ssl/apache.key
      - app_logs:/var/www/var/log
      - app_sessions:/var/www/var/cache/prod/sessions
    ports:
      - "80:80"
      - "${APACHE_SSL_PORT:-443}:443"
    depends_on:
      - database
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  database:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_SCHEDULE=0 0 * * * # Run once a day at midnight
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN:-mytoken}
      - WATCHTOWER_HTTP_API_METRICS=true
    ports:
      - "8080:8080"
    command: --http-api-update

volumes:
  database_data:
  app_logs:
  app_sessions:
