version: '3.8'

services:
  php:
    image: ${DOCKER_REGISTRY:-localhost}/reliquary-php:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=15&charset=utf8
    volumes:
      - php_socket:/var/run/php
      - ./public:/srv/app/public:ro
      - ./var:/srv/app/var:rw
    depends_on:
      - database

  nginx:
    image: ${DOCKER_REGISTRY:-localhost}/reliquary-nginx:${IMAGE_TAG:-latest}
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - php_socket:/var/run/php
      - ./public:/srv/app/public:ro

  database:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  php_socket:
  database_data: