name: Build and Deploy Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Apache+PHP image
        id: meta-apache
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/reliquary
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short

      - name: Build and push Apache+PHP image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/apache/Dockerfile.prod
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-apache.outputs.tags }}
          labels: ${{ steps.meta-apache.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
